'use strict';

// Flag types:
//   horizontal_stripes  — colors top to bottom
//   vertical_stripes    — colors left to right
//   nordic_cross        — bg + crossH (outer) + crossV (inner), offsetRatio = cross center from left (0–1)
//   solid_with_emblem   — bg + emblem {shape, color, offsetX, offsetY, size (fraction of radius)}
//   diagonal            — colors[0] top-left triangle, colors[1] bottom-right
//   cross               — bg + crossColor (equal-arm cross, centered)
//   quartered           — four quadrant colors [TL, TR, BL, BR]
//   solid               — single color fill
//   union_jack          — special: UK flag

const CHARACTERS = [
    // ── STARTER ──────────────────────────────────────────────────────────
    { code:'PL', name:'Poland',         rarity:'starter',   price:0,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#dc143c'] } },

    // ── COMMON (100 coins) ───────────────────────────────────────────────
    { code:'DE', name:'Germany',        rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#000000','#dd0000','#ffce00'] } },
    { code:'FR', name:'France',         rarity:'common',    price:100,
      flag:{ type:'vertical_stripes',   colors:['#002395','#ffffff','#ed2939'] } },
    { code:'IT', name:'Italy',          rarity:'common',    price:100,
      flag:{ type:'vertical_stripes',   colors:['#009246','#ffffff','#ce2b37'] } },
    { code:'ES', name:'Spain',          rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#aa151b','#f1bf00','#aa151b'] } },
    { code:'US', name:'United States',  rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#B22234','#ffffff','#B22234','#ffffff','#B22234','#ffffff','#B22234','#3C3B6E','#3C3B6E'] } },
    { code:'RU', name:'Russia',         rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#1c3578','#d52b1e'] } },
    { code:'CN', name:'China',          rarity:'common',    price:100,
      flag:{ type:'solid_with_emblem',  bg:'#de2910',
             emblem:{ shape:'star', color:'#ffde00', offsetX:-0.3, offsetY:-0.25, size:0.38 } } },
    { code:'JP', name:'Japan',          rarity:'common',    price:100,
      flag:{ type:'solid_with_emblem',  bg:'#ffffff',
             emblem:{ shape:'circle', color:'#bc002d', offsetX:0, offsetY:0, size:0.42 } } },
    { code:'GB', name:'United Kingdom', rarity:'common',    price:100,
      flag:{ type:'union_jack' } },
    { code:'CA', name:'Canada',         rarity:'common',    price:100,
      flag:{ type:'vertical_stripes',   colors:['#ff0000','#ffffff','#ff0000'],
             emblem:{ shape:'maple', color:'#ff0000', offsetX:0, offsetY:0, size:0.45 } } },
    { code:'AU', name:'Australia',      rarity:'common',    price:100,
      flag:{ type:'solid_with_emblem',  bg:'#00008b',
             emblem:{ shape:'star', color:'#ffffff', offsetX:0.2, offsetY:0.2, size:0.3 } } },
    { code:'BR', name:'Brazil',         rarity:'common',    price:100,
      flag:{ type:'solid_with_emblem',  bg:'#009c3b',
             emblem:{ shape:'diamond', color:'#fedf00', offsetX:0, offsetY:0, size:0.7 } } },
    { code:'IN', name:'India',          rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#ff9933','#ffffff','#138808'],
             emblem:{ shape:'circle', color:'#000080', offsetX:0, offsetY:0, size:0.18 } } },
    { code:'MX', name:'Mexico',         rarity:'common',    price:100,
      flag:{ type:'vertical_stripes',   colors:['#006847','#ffffff','#ce1126'] } },
    { code:'AR', name:'Argentina',      rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#74acdf','#ffffff','#74acdf'] } },
    { code:'ZA', name:'South Africa',   rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#007a4d','#ffffff','#de3831','#002395','#002395','#ffb612'] } },
    { code:'NG', name:'Nigeria',        rarity:'common',    price:100,
      flag:{ type:'vertical_stripes',   colors:['#008751','#ffffff','#008751'] } },
    { code:'EG', name:'Egypt',          rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#ce1126','#ffffff','#000000'] } },
    { code:'TR', name:'Turkey',         rarity:'common',    price:100,
      flag:{ type:'solid_with_emblem',  bg:'#e30a17',
             emblem:{ shape:'crescent', color:'#ffffff', offsetX:-0.05, offsetY:0, size:0.45 } } },
    { code:'KR', name:'South Korea',    rarity:'common',    price:100,
      flag:{ type:'solid_with_emblem',  bg:'#ffffff',
             emblem:{ shape:'taeguk', color:'#cd2e3a', offsetX:0, offsetY:0, size:0.4 } } },
    { code:'SA', name:'Saudi Arabia',   rarity:'common',    price:100,
      flag:{ type:'solid_with_emblem',  bg:'#006c35',
             emblem:{ shape:'sword', color:'#ffffff', offsetX:0, offsetY:0, size:0.5 } } },
    { code:'ID', name:'Indonesia',      rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#ce1126','#ffffff'] } },
    { code:'UA', name:'Ukraine',        rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#005bbb','#ffd500'] } },
    { code:'NL', name:'Netherlands',    rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#ae1c28','#ffffff','#21468b'] } },
    { code:'PT', name:'Portugal',       rarity:'common',    price:100,
      flag:{ type:'vertical_stripes',   colors:['#006600','#ff0000'],
             splitRatio: 0.38 } },
    { code:'SE', name:'Sweden',         rarity:'common',    price:100,
      flag:{ type:'nordic_cross',       bg:'#006aa7', crossH:'#fecc02', crossV:'#fecc02', offsetRatio:0.38 } },
    { code:'NO', name:'Norway',         rarity:'common',    price:100,
      flag:{ type:'nordic_cross',       bg:'#ef2b2d', crossH:'#ffffff', crossV:'#002868', offsetRatio:0.38 } },
    { code:'DK', name:'Denmark',        rarity:'common',    price:100,
      flag:{ type:'nordic_cross',       bg:'#c60c30', crossH:'#ffffff', crossV:'#ffffff', offsetRatio:0.38 } },
    { code:'FI', name:'Finland',        rarity:'common',    price:100,
      flag:{ type:'nordic_cross',       bg:'#ffffff', crossH:'#003580', crossV:'#003580', offsetRatio:0.38 } },
    { code:'CH', name:'Switzerland',    rarity:'common',    price:100,
      flag:{ type:'solid_with_emblem',  bg:'#ff0000',
             emblem:{ shape:'cross', color:'#ffffff', offsetX:0, offsetY:0, size:0.55 } } },
    { code:'AT', name:'Austria',        rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#ed2939','#ffffff','#ed2939'] } },
    { code:'BE', name:'Belgium',        rarity:'common',    price:100,
      flag:{ type:'vertical_stripes',   colors:['#000000','#fae042','#ef3340'] } },
    { code:'GR', name:'Greece',         rarity:'common',    price:100,
      flag:{ type:'horizontal_stripes', colors:['#0d5eaf','#ffffff','#0d5eaf','#ffffff','#0d5eaf','#ffffff','#0d5eaf','#ffffff','#0d5eaf'] } },
    { code:'PK', name:'Pakistan',       rarity:'common',    price:100,
      flag:{ type:'vertical_stripes',   colors:['#ffffff','#01411c'], splitRatio:0.25,
             emblem:{ shape:'crescent', color:'#ffffff', offsetX:0.15, offsetY:0, size:0.4 } } },

    // ── UNCOMMON (250 coins) ─────────────────────────────────────────────
    { code:'TH', name:'Thailand',       rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#a51931','#f4f5f8','#2d2a4a','#f4f5f8','#a51931'] } },
    { code:'PH', name:'Philippines',    rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#0038a8','#ce1126'],
             emblem:{ shape:'sun', color:'#fcd116', offsetX:-0.3, offsetY:0, size:0.35 } } },
    { code:'MY', name:'Malaysia',       rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#cc0001','#ffffff','#cc0001','#ffffff','#cc0001','#ffffff','#cc0001','#ffffff','#cc0001','#ffffff','#cc0001','#ffffff','#cc0001','#010094','#010094'] } },
    { code:'VN', name:'Vietnam',        rarity:'uncommon',  price:250,
      flag:{ type:'solid_with_emblem',  bg:'#da251d',
             emblem:{ shape:'star', color:'#ffff00', offsetX:0, offsetY:0, size:0.45 } } },
    { code:'SG', name:'Singapore',      rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#ef3340','#ffffff'],
             emblem:{ shape:'crescent', color:'#ffffff', offsetX:-0.2, offsetY:-0.15, size:0.3 } } },
    { code:'KE', name:'Kenya',          rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#006600','#ffffff','#bb0000','#ffffff','#006600'] } },
    { code:'GH', name:'Ghana',          rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#006b3f','#fcd116','#ce1126'],
             emblem:{ shape:'star', color:'#000000', offsetX:0, offsetY:0, size:0.2 } } },
    { code:'ET', name:'Ethiopia',       rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#078930','#fcdd09','#da121a'] } },
    { code:'MA', name:'Morocco',        rarity:'uncommon',  price:250,
      flag:{ type:'solid_with_emblem',  bg:'#c1272d',
             emblem:{ shape:'star_outline', color:'#006233', offsetX:0, offsetY:0, size:0.4 } } },
    { code:'DZ', name:'Algeria',        rarity:'uncommon',  price:250,
      flag:{ type:'vertical_stripes',   colors:['#006233','#ffffff'],
             emblem:{ shape:'crescent', color:'#d21034', offsetX:0.05, offsetY:0, size:0.38 } } },
    { code:'TN', name:'Tunisia',        rarity:'uncommon',  price:250,
      flag:{ type:'solid_with_emblem',  bg:'#e70013',
             emblem:{ shape:'crescent', color:'#ffffff', offsetX:0, offsetY:0, size:0.42 } } },
    { code:'IQ', name:'Iraq',           rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#ce1126','#ffffff','#000000'] } },
    { code:'IR', name:'Iran',           rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#239f40','#ffffff','#da0000'] } },
    { code:'IL', name:'Israel',         rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#0038b8','#ffffff','#ffffff','#ffffff','#0038b8'] } },
    { code:'AE', name:'UAE',            rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#00732f','#ffffff','#000000'],
             emblem:{ shape:'rect', color:'#ff0000', offsetX:-0.38, offsetY:0, size:0.22 } } },
    { code:'PL2', name:'Palestine',     rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#000000','#ffffff','#007a3d'],
             emblem:{ shape:'triangle', color:'#ce1126', offsetX:-0.35, offsetY:0, size:0.45 } } },
    { code:'CO', name:'Colombia',       rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#fcd116','#fcd116','#003087','#ce1126'] } },
    { code:'VE', name:'Venezuela',      rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#cf142b','#00247d','#f4e20d'] } },
    { code:'PE', name:'Peru',           rarity:'uncommon',  price:250,
      flag:{ type:'vertical_stripes',   colors:['#d91023','#ffffff','#d91023'] } },
    { code:'CL', name:'Chile',          rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#d52b1e','#ffffff'],
             emblem:{ shape:'star', color:'#ffffff', offsetX:-0.32, offsetY:0.25, size:0.22 } } },
    { code:'CU', name:'Cuba',           rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#002a8f','#ffffff','#002a8f','#ffffff','#002a8f'],
             emblem:{ shape:'triangle', color:'#cc0a00', offsetX:-0.35, offsetY:0, size:0.5 } } },
    { code:'RO', name:'Romania',        rarity:'uncommon',  price:250,
      flag:{ type:'vertical_stripes',   colors:['#002b7f','#fcd116','#ce1126'] } },
    { code:'HU', name:'Hungary',        rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#ce2939','#ffffff','#477050'] } },
    { code:'CZ', name:'Czechia',        rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#d7141a'],
             emblem:{ shape:'triangle', color:'#11457e', offsetX:-0.3, offsetY:0, size:0.6 } } },
    { code:'SK', name:'Slovakia',       rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#0b4ea2','#ee1c25'] } },
    { code:'HR', name:'Croatia',        rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#ff0000','#ffffff','#0000ff'] } },
    { code:'RS', name:'Serbia',         rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#c6363c','#0c4076','#ffffff'] } },
    { code:'BG', name:'Bulgaria',       rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#00966e','#d62512'] } },
    { code:'LT', name:'Lithuania',      rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#fdb913','#006a44','#c1272d'] } },
    { code:'LV', name:'Latvia',         rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#9e3039','#ffffff','#9e3039'] } },
    { code:'EE', name:'Estonia',        rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#0072ce','#000000','#ffffff'] } },
    { code:'IS', name:'Iceland',        rarity:'uncommon',  price:250,
      flag:{ type:'nordic_cross',       bg:'#003897', crossH:'#ffffff', crossV:'#d72828', offsetRatio:0.38 } },
    { code:'IE', name:'Ireland',        rarity:'uncommon',  price:250,
      flag:{ type:'vertical_stripes',   colors:['#169b62','#ffffff','#ff883e'] } },
    { code:'NZ', name:'New Zealand',    rarity:'uncommon',  price:250,
      flag:{ type:'solid_with_emblem',  bg:'#00247d',
             emblem:{ shape:'stars4', color:'#cc142b', offsetX:0.1, offsetY:0.1, size:0.5 } } },
    { code:'CL2', name:'Sri Lanka',     rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#ff7300','#006241','#8d153a'] } },
    { code:'BD', name:'Bangladesh',     rarity:'uncommon',  price:250,
      flag:{ type:'solid_with_emblem',  bg:'#006a4e',
             emblem:{ shape:'circle', color:'#f42a41', offsetX:-0.08, offsetY:0, size:0.42 } } },
    { code:'MM', name:'Myanmar',        rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#fecb00','#34b233','#ea2839'] } },
    { code:'KH', name:'Cambodia',       rarity:'uncommon',  price:250,
      flag:{ type:'horizontal_stripes', colors:['#032ea1','#e00025','#032ea1'] } },

    // ── RARE (500 coins) ─────────────────────────────────────────────────
    { code:'BT', name:'Bhutan',         rarity:'rare',      price:500,
      flag:{ type:'diagonal',           colors:['#ff8000','#e5252d'] } },
    { code:'NP', name:'Nepal',          rarity:'rare',      price:500,
      flag:{ type:'solid_with_emblem',  bg:'#003893',
             emblem:{ shape:'pennant', color:'#ffffff', offsetX:0, offsetY:0, size:0.6 } } },
    { code:'LB', name:'Lebanon',        rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#cc0000','#ffffff','#cc0000','#ffffff'] } },
    { code:'JO', name:'Jordan',         rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#007a3d','#ffffff','#000000'],
             emblem:{ shape:'star', color:'#ffffff', offsetX:-0.3, offsetY:0, size:0.2 } } },
    { code:'SY', name:'Syria',          rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ce1126','#ffffff','#000000'] } },
    { code:'YE', name:'Yemen',          rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ce1126','#ffffff','#000000'] } },
    { code:'LY', name:'Libya',          rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#000000','#ffffff','#239e46'] } },
    { code:'SD', name:'Sudan',          rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#d21034','#ffffff','#000000'],
             emblem:{ shape:'triangle', color:'#007229', offsetX:-0.35, offsetY:0, size:0.5 } } },
    { code:'SN', name:'Senegal',        rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#00853f','#fdef42','#e31b23'],
             emblem:{ shape:'star', color:'#00853f', offsetX:0, offsetY:0, size:0.22 } } },
    { code:'CI', name:"Côte d'Ivoire",  rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#f77f00','#ffffff','#009a44'] } },
    { code:'CM', name:'Cameroon',       rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#007a5e','#ce1126','#fcd116'] } },
    { code:'TZ', name:'Tanzania',       rarity:'rare',      price:500,
      flag:{ type:'diagonal',           colors:['#1eb53a','#00a3dd'] } },
    { code:'UG', name:'Uganda',         rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#000000','#fcdc04','#de3108','#000000','#fcdc04','#de3108'] } },
    { code:'ZW', name:'Zimbabwe',       rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#006400','#ffd200','#d40000','#000000','#d40000','#ffd200','#006400'] } },
    { code:'MW', name:'Malawi',         rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#000000','#ce2028','#339e35'] } },
    { code:'ZM', name:'Zambia',         rarity:'rare',      price:500,
      flag:{ type:'solid_with_emblem',  bg:'#198a00',
             emblem:{ shape:'eagle', color:'#ef7d00', offsetX:0.3, offsetY:-0.25, size:0.35 } } },
    { code:'MZ', name:'Mozambique',     rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#009a44','#ffffff','#fce100','#ffffff','#000000'],
             emblem:{ shape:'triangle', color:'#d21034', offsetX:-0.35, offsetY:0, size:0.5 } } },
    { code:'AO', name:'Angola',         rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#cc0000','#000000'] } },
    { code:'KZ', name:'Kazakhstan',     rarity:'rare',      price:500,
      flag:{ type:'solid_with_emblem',  bg:'#00afca',
             emblem:{ shape:'sun', color:'#ffe200', offsetX:0.1, offsetY:-0.1, size:0.35 } } },
    { code:'UZ', name:'Uzbekistan',     rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#1eb53a','#ffffff','#ce1126','#ffffff','#0099b5'] } },
    { code:'GE', name:'Georgia',        rarity:'rare',      price:500,
      flag:{ type:'cross',              bg:'#ffffff', crossColor:'#ff0000' } },
    { code:'AM', name:'Armenia',        rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#d90012','#0033a0','#f2a800'] } },
    { code:'AZ', name:'Azerbaijan',     rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#0092bc','#e8001e','#00af51'],
             emblem:{ shape:'crescent', color:'#ffffff', offsetX:0, offsetY:0, size:0.35 } } },
    { code:'BY', name:'Belarus',        rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#cf101a','#007526','#cf101a'] } },
    { code:'MD', name:'Moldova',        rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#003DA5','#FAE042','#CC0001'] } },
    { code:'AL', name:'Albania',        rarity:'rare',      price:500,
      flag:{ type:'solid_with_emblem',  bg:'#e41e20',
             emblem:{ shape:'eagle2head', color:'#000000', offsetX:0, offsetY:0, size:0.55 } } },
    { code:'MK', name:'N. Macedonia',   rarity:'rare',      price:500,
      flag:{ type:'solid_with_emblem',  bg:'#ce2028',
             emblem:{ shape:'sun_rays', color:'#f7ca18', offsetX:0, offsetY:0, size:0.6 } } },
    { code:'BA', name:'Bosnia',         rarity:'rare',      price:500,
      flag:{ type:'diagonal',           colors:['#003087','#003087'],
             emblem:{ shape:'triangle', color:'#fecb00', offsetX:0, offsetY:0, size:0.6 } } },
    { code:'SI', name:'Slovenia',       rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#003da5','#ffffff','#e4231b'] } },
    { code:'LU', name:'Luxembourg',     rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ef3340','#ffffff','#00a1de'] } },
    { code:'MC', name:'Monaco',         rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ce1126','#ffffff'] } },
    { code:'LI', name:'Liechtenstein',  rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#002b7f','#ce1126'],
             emblem:{ shape:'crown', color:'#ffd83d', offsetX:-0.2, offsetY:-0.15, size:0.25 } } },
    { code:'MT', name:'Malta',          rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#ffffff','#cf142b'] } },
    { code:'CY', name:'Cyprus',         rarity:'rare',      price:500,
      flag:{ type:'solid_with_emblem',  bg:'#ffffff',
             emblem:{ shape:'map', color:'#d57800', offsetX:0, offsetY:-0.1, size:0.55 } } },
    { code:'LK', name:'Sri Lanka',      rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ff7300','#006241','#8d153a'] } },
    { code:'NE', name:'Niger',          rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#e05206','#ffffff','#0db02b'],
             emblem:{ shape:'circle', color:'#e05206', offsetX:0, offsetY:0, size:0.2 } } },
    { code:'ML', name:'Mali',           rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#14b53a','#fcd116','#ce1126'] } },
    { code:'BF', name:'Burkina Faso',   rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ef2b2d','#009a00'],
             emblem:{ shape:'star', color:'#fcd116', offsetX:0, offsetY:0, size:0.22 } } },
    { code:'GN', name:'Guinea',         rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#ce1126','#fcd116','#009460'] } },
    { code:'TD', name:'Chad',           rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#002664','#fecb00','#c60c30'] } },
    { code:'CF', name:'C. African Rep.',rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#003082','#ffffff','#289728','#ffcb00'],
             emblem:{ shape:'stripe_v', color:'#bc0026', offsetX:0, offsetY:0, size:0.12 } } },
    { code:'CG', name:'Congo',          rarity:'rare',      price:500,
      flag:{ type:'diagonal',           colors:['#009543','#fbde4a','#dc241f'] } },
    { code:'CD', name:'DR Congo',       rarity:'rare',      price:500,
      flag:{ type:'diagonal',           colors:['#007fff','#f7d618','#ce1021'] } },
    { code:'RW', name:'Rwanda',         rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#20603d','#fad201','#20603d','#20603d','#009cde'],
             emblem:{ shape:'sun', color:'#fad201', offsetX:0.25, offsetY:-0.2, size:0.28 } } },
    { code:'BO', name:'Bolivia',        rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#d52b1e','#f4e400','#007934'] } },
    { code:'PY', name:'Paraguay',       rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#d52b1e','#ffffff','#009bde'] } },
    { code:'UY', name:'Uruguay',        rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#5dbde6','#ffffff','#5dbde6','#ffffff','#5dbde6','#ffffff','#5dbde6','#ffffff'] } },
    { code:'EC', name:'Ecuador',        rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#ffda00','#ffda00','#003893','#c8102e'] } },
    { code:'GT', name:'Guatemala',      rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#4997d0','#ffffff','#4997d0'] } },
    { code:'HN', name:'Honduras',       rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#0073cf','#ffffff','#0073cf'] } },
    { code:'CR', name:'Costa Rica',     rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#002b7f','#ffffff','#c09300','#ffffff','#002b7f'] } },
    { code:'PA', name:'Panama',         rarity:'rare',      price:500,
      flag:{ type:'quartered',          colors:['#ffffff','#d21034','#0038a8','#ffffff'] } },
    { code:'DO', name:'Dominican Rep.', rarity:'rare',      price:500,
      flag:{ type:'quartered',          colors:['#002d62','#ce1126','#ce1126','#002d62'],
             emblem:{ shape:'cross', color:'#ffffff', offsetX:0, offsetY:0, size:0.4 } } },
    { code:'JM', name:'Jamaica',        rarity:'rare',      price:500,
      flag:{ type:'diagonal',           colors:['#000000','#009b3a'],
             emblem:{ shape:'cross_diag', color:'#ffd100', offsetX:0, offsetY:0, size:0.15 } } },
    { code:'TT', name:'Trinidad & Tobago', rarity:'rare',   price:500,
      flag:{ type:'diagonal',           colors:['#ce1126','#000000'],
             emblem:{ shape:'stripe_diag', color:'#000000', offsetX:0, offsetY:0, size:0.15 } } },
    { code:'KW', name:'Kuwait',         rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#007a3d','#ffffff','#ce1126'],
             emblem:{ shape:'trapezoid', color:'#000000', offsetX:-0.35, offsetY:0, size:0.35 } } },
    { code:'QA', name:'Qatar',          rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#8d1b3d','#ffffff'], splitRatio:0.75 } },
    { code:'BH', name:'Bahrain',        rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#ce1126','#ffffff'], splitRatio:0.75 } },
    { code:'OM', name:'Oman',           rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#db161b','#ffffff','#008000'],
             emblem:{ shape:'rect', color:'#db161b', offsetX:-0.38, offsetY:0, size:0.22 } } },
    { code:'MN', name:'Mongolia',       rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#c4272f','#003087','#c4272f'],
             emblem:{ shape:'soyombo', color:'#f9bc1b', offsetX:-0.28, offsetY:0, size:0.45 } } },
    { code:'KG', name:'Kyrgyzstan',     rarity:'rare',      price:500,
      flag:{ type:'solid_with_emblem',  bg:'#e8112d',
             emblem:{ shape:'sun_round', color:'#fbbf17', offsetX:0, offsetY:0, size:0.48 } } },
    { code:'TJ', name:'Tajikistan',     rarity:'rare',      price:500,
      flag:{ type:'horizontal_stripes', colors:['#cc0000','#ffffff','#006600'] } },
    { code:'TM', name:'Turkmenistan',   rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#1a9e1c','#ffffff'], splitRatio:0.25 } },
    { code:'AF', name:'Afghanistan',    rarity:'rare',      price:500,
      flag:{ type:'vertical_stripes',   colors:['#000000','#ffffff','#007a36'] } },

    // ── LEGENDARY (1000 coins) ───────────────────────────────────────────
    { code:'VA', name:'Vatican City',   rarity:'legendary', price:1000,
      flag:{ type:'vertical_stripes',   colors:['#ffe000','#ffffff'] } },
    { code:'SM', name:'San Marino',     rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#5EB6E4','#ffffff'] } },
    { code:'AD', name:'Andorra',        rarity:'legendary', price:1000,
      flag:{ type:'vertical_stripes',   colors:['#003DA5','#FEDF00','#C7312A'] } },
    { code:'SC', name:'Seychelles',     rarity:'legendary', price:1000,
      flag:{ type:'diagonal',           colors:['#003f87','#fcd856','#d62828','#ffffff','#007a00'] } },
    { code:'KM', name:'Comoros',        rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#3a75c4','#ffffff','#ff0000','#009a00'] } },
    { code:'MV', name:'Maldives',       rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#d21034',
             emblem:{ shape:'crescent', color:'#ffffff', offsetX:0, offsetY:0, size:0.45 } } },
    { code:'BN', name:'Brunei',         rarity:'legendary', price:1000,
      flag:{ type:'diagonal',           colors:['#f7e017','#000000','#f7e017'],
             emblem:{ shape:'crest', color:'#ffffff', offsetX:0, offsetY:0, size:0.45 } } },
    { code:'PG', name:'Papua New Guinea',rarity:'legendary',price:1000,
      flag:{ type:'diagonal',           colors:['#000000','#ce1126'] } },
    { code:'FJ', name:'Fiji',           rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#68bfe5',
             emblem:{ shape:'shield', color:'#ffffff', offsetX:0.1, offsetY:0, size:0.45 } } },
    { code:'WS', name:'Samoa',          rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#ce1126',
             emblem:{ shape:'stars5', color:'#ffffff', offsetX:0.15, offsetY:0, size:0.45 } } },
    { code:'TO', name:'Tonga',          rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#c10000',
             emblem:{ shape:'cross', color:'#c10000', offsetX:-0.3, offsetY:-0.25, size:0.3 } } },
    { code:'VU', name:'Vanuatu',        rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#009543','#d21034'],
             emblem:{ shape:'triangle', color:'#000000', offsetX:-0.35, offsetY:0, size:0.6 } } },
    { code:'SB', name:'Solomon Islands',rarity:'legendary', price:1000,
      flag:{ type:'diagonal',           colors:['#0120A2','#007229'] } },
    { code:'KI', name:'Kiribati',       rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#ce1126','#003f87'],
             emblem:{ shape:'sun_rays', color:'#ffd100', offsetX:0, offsetY:-0.15, size:0.5 } } },
    { code:'TV', name:'Tuvalu',         rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#009fca',
             emblem:{ shape:'stars9', color:'#ffffff', offsetX:0.1, offsetY:0.1, size:0.6 } } },
    { code:'NR', name:'Nauru',          rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#002b7f',
             emblem:{ shape:'star', color:'#ffffff', offsetX:0.15, offsetY:0.35, size:0.22 } } },
    { code:'PW', name:'Palau',          rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#4aadd6',
             emblem:{ shape:'circle', color:'#ffde00', offsetX:-0.08, offsetY:0, size:0.42 } } },
    { code:'MH', name:'Marshall Islands',rarity:'legendary',price:1000,
      flag:{ type:'diagonal',           colors:['#003087','#ff8c00'] } },
    { code:'FM', name:'Micronesia',     rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#75b2dd',
             emblem:{ shape:'stars4', color:'#ffffff', offsetX:0, offsetY:0, size:0.55 } } },
    { code:'CK', name:'Cook Islands',   rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#00247d',
             emblem:{ shape:'stars15', color:'#ffffff', offsetX:0.1, offsetY:0, size:0.55 } } },
    { code:'NU', name:'Niue',           rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#ffd100',
             emblem:{ shape:'stars5', color:'#ffd100', offsetX:0.1, offsetY:0, size:0.45 } } },
    // Territories & special
    { code:'HK', name:'Hong Kong',      rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#de2110',
             emblem:{ shape:'flower5', color:'#ffffff', offsetX:0, offsetY:0, size:0.45 } } },
    { code:'TW', name:'Taiwan',         rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#fe0000',
             emblem:{ shape:'sun12', color:'#ffffff', offsetX:-0.25, offsetY:-0.25, size:0.3 } } },
    { code:'PR', name:'Puerto Rico',    rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#bd0029','#ffffff','#bd0029','#ffffff','#bd0029'],
             emblem:{ shape:'triangle', color:'#0d0cde', offsetX:-0.35, offsetY:0, size:0.55 } } },
    { code:'GI', name:'Gibraltar',      rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#da291c'] } },
    { code:'GL', name:'Greenland',      rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#d00c33'],
             emblem:{ shape:'circle_half', color:'#d00c33', offsetX:0, offsetY:0, size:0.42 } } },
    { code:'FO', name:'Faroe Islands',  rarity:'legendary', price:1000,
      flag:{ type:'nordic_cross',       bg:'#ffffff', crossH:'#003897', crossV:'#ed2939', offsetRatio:0.38 } },
    { code:'AX', name:'Åland Islands',  rarity:'legendary', price:1000,
      flag:{ type:'nordic_cross',       bg:'#0053a5', crossH:'#ffd83d', crossV:'#e8112d', offsetRatio:0.38 } },
    { code:'SJ', name:'Svalbard',       rarity:'legendary', price:1000,
      flag:{ type:'nordic_cross',       bg:'#ef2b2d', crossH:'#ffffff', crossV:'#002868', offsetRatio:0.38 } },
    { code:'TF', name:'French S. Territories', rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#002395','#ffffff','#ed2939'] } },
    { code:'PM', name:'St. Pierre & Miquelon', rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#003082','#ffffff','#003082'] } },
    // Micronations / special
    { code:'XS', name:'Sealand',        rarity:'legendary', price:1000,
      flag:{ type:'diagonal',           colors:['#000000','#ff0000'],
             emblem:{ shape:'stripe_h', color:'#ffffff', offsetX:0, offsetY:0.35, size:0.2 } } },
    { code:'XT', name:'Transnistria',   rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#cc0000','#009a00','#cc0000'],
             emblem:{ shape:'star', color:'#ffcc00', offsetX:0, offsetY:0, size:0.2 } } },
    { code:'XK', name:'Kosovo',         rarity:'legendary', price:1000,
      flag:{ type:'solid_with_emblem',  bg:'#244aa5',
             emblem:{ shape:'map_ko', color:'#e4c14a', offsetX:0, offsetY:-0.1, size:0.5 } } },
    { code:'XA', name:'Abkhazia',       rarity:'legendary', price:1000,
      flag:{ type:'horizontal_stripes', colors:['#3e9a2b','#ffffff','#3e9a2b','#ffffff','#3e9a2b','#ffffff','#3e9a2b'],
             emblem:{ shape:'hand', color:'#ffffff', offsetX:-0.2, offsetY:0, size:0.3 } } },

    // ── MYSTICAL (2500 coins) ────────────────────────────────────────────
    // Sub-national flags
    { code:'EU',  name:'European Union', rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#003399',
             emblem:{ shape:'sun_rays', color:'#ffcc00', offsetX:0, offsetY:0, size:0.6 } } },
    { code:'UN',  name:'United Nations', rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#4b92db',
             emblem:{ shape:'circle', color:'#ffffff', offsetX:0, offsetY:0, size:0.45 } } },
    { code:'SCT', name:'Scotland',       rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#003399',
             emblem:{ shape:'cross', color:'#ffffff', offsetX:0, offsetY:0, size:0.6 } } },
    { code:'WLS', name:'Wales',          rarity:'mystical',  price:2500,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#00ab39'] } },
    { code:'CAT', name:'Catalonia',      rarity:'mystical',  price:2500,
      flag:{ type:'horizontal_stripes', colors:['#fcdd09','#c60b1e','#fcdd09','#c60b1e','#fcdd09','#c60b1e','#fcdd09','#c60b1e','#fcdd09'] } },
    { code:'QBC', name:'Quebec',         rarity:'mystical',  price:2500,
      flag:{ type:'quartered',          colors:['#ffffff','#002395','#002395','#ffffff'] } },
    { code:'BAV', name:'Bavaria',        rarity:'mystical',  price:2500,
      flag:{ type:'quartered',          colors:['#ffffff','#009ee0','#009ee0','#ffffff'] } },
    { code:'OKI', name:'Okinawa',        rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#ffffff',
             emblem:{ shape:'circle', color:'#009b77', offsetX:0, offsetY:0, size:0.38 } } },
    // US States
    { code:'USTX', name:'Texas',         rarity:'mystical',  price:2500,
      flag:{ type:'vertical_stripes',   colors:['#002868','#ffffff','#bf0a30'],
             emblem:{ shape:'star', color:'#ffffff', offsetX:-0.32, offsetY:0, size:0.3 } } },
    { code:'USCA', name:'California',    rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#003087',
             emblem:{ shape:'star', color:'#ffcc00', offsetX:0, offsetY:0, size:0.42 } } },
    { code:'USNY', name:'New York',      rarity:'mystical',  price:2500,
      flag:{ type:'vertical_stripes',   colors:['#003087','#ffcc00','#003087'] } },
    { code:'USFL', name:'Florida',       rarity:'mystical',  price:2500,
      flag:{ type:'cross',              bg:'#ffffff', crossColor:'#c41230' } },
    { code:'USMD', name:'Maryland',      rarity:'mystical',  price:2500,
      flag:{ type:'quartered',          colors:['#000000','#f5a623','#c4122a','#f5f5f5'] } },
    { code:'USNM', name:'New Mexico',    rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#ffcc00',
             emblem:{ shape:'sun', color:'#c41230', offsetX:0, offsetY:0, size:0.48 } } },
    { code:'USCO', name:'Colorado',      rarity:'mystical',  price:2500,
      flag:{ type:'horizontal_stripes', colors:['#002868','#ffffff','#002868'],
             emblem:{ shape:'circle', color:'#e31c3d', offsetX:-0.2, offsetY:0, size:0.32 } } },
    { code:'USAK', name:'Alaska',        rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#003087',
             emblem:{ shape:'stars4', color:'#ffcc00', offsetX:0.1, offsetY:-0.1, size:0.5 } } },
    { code:'USHI', name:'Hawaii',        rarity:'mystical',  price:2500,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#c41230','#ffffff','#003087','#ffffff','#c41230','#ffffff','#003087'] } },
    { code:'USSC', name:'South Carolina',rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#003087',
             emblem:{ shape:'crescent', color:'#ffffff', offsetX:-0.15, offsetY:-0.2, size:0.3 } } },
    { code:'USTN', name:'Tennessee',     rarity:'mystical',  price:2500,
      flag:{ type:'solid_with_emblem',  bg:'#c41230',
             emblem:{ shape:'circle', color:'#003087', offsetX:0, offsetY:0, size:0.38 } } },

    // ── GODLY (10000 coins) ──────────────────────────────────────────────
    // Major world cities
    { code:'NYC', name:'New York City',  rarity:'godly',     price:10000,
      flag:{ type:'vertical_stripes',   colors:['#003087','#ffffff','#ff6600'] } },
    { code:'LON', name:'London',         rarity:'godly',     price:10000,
      flag:{ type:'cross',              bg:'#ffffff', crossColor:'#c41230' } },
    { code:'PAR', name:'Paris',          rarity:'godly',     price:10000,
      flag:{ type:'vertical_stripes',   colors:['#003087','#ffffff','#c41230'],
             emblem:{ shape:'fleur', color:'#ffd700', offsetX:0, offsetY:0, size:0.28 } } },
    { code:'TOK', name:'Tokyo',          rarity:'godly',     price:10000,
      flag:{ type:'solid_with_emblem',  bg:'#009b77',
             emblem:{ shape:'circle', color:'#ffffff', offsetX:0, offsetY:0, size:0.42 } } },
    { code:'BER', name:'Berlin',         rarity:'godly',     price:10000,
      flag:{ type:'horizontal_stripes', colors:['#c41230','#ffffff','#000000'],
             emblem:{ shape:'star', color:'#c41230', offsetX:0, offsetY:0, size:0.28 } } },
    { code:'ROM', name:'Rome',           rarity:'godly',     price:10000,
      flag:{ type:'vertical_stripes',   colors:['#ffcc00','#c41230'] } },
    { code:'SYD', name:'Sydney',         rarity:'godly',     price:10000,
      flag:{ type:'solid_with_emblem',  bg:'#00529b',
             emblem:{ shape:'star', color:'#ffffff', offsetX:0, offsetY:0, size:0.42 } } },
    { code:'RIO', name:'Rio de Janeiro', rarity:'godly',     price:10000,
      flag:{ type:'solid_with_emblem',  bg:'#009c3b',
             emblem:{ shape:'diamond', color:'#fedf00', offsetX:0, offsetY:0, size:0.65 } } },
    { code:'DXB', name:'Dubai',          rarity:'godly',     price:10000,
      flag:{ type:'horizontal_stripes', colors:['#009b3a','#ffffff','#000000'],
             emblem:{ shape:'rect', color:'#c41230', offsetX:-0.38, offsetY:0, size:0.22 } } },
    { code:'MOS', name:'Moscow',         rarity:'godly',     price:10000,
      flag:{ type:'horizontal_stripes', colors:['#ffffff','#c41230','#ffcc00'] } },
    { code:'BJG', name:'Beijing',        rarity:'godly',     price:10000,
      flag:{ type:'solid_with_emblem',  bg:'#c41230',
             emblem:{ shape:'star', color:'#ffde00', offsetX:-0.2, offsetY:-0.2, size:0.42 } } },
    { code:'IST', name:'Istanbul',       rarity:'godly',     price:10000,
      flag:{ type:'solid_with_emblem',  bg:'#c41230',
             emblem:{ shape:'crescent', color:'#ffffff', offsetX:0, offsetY:0, size:0.45 } } },
];

// Build fast lookup map
const CharacterMap = new Map(CHARACTERS.map(c => [c.code, c]));

const RARITY_ORDER = ['starter', 'common', 'uncommon', 'rare', 'legendary', 'mystical', 'godly'];
